cards:
  welcome:
    title: Welcome to the Private Notifications Center
    text: ""

  unknown:
    title: ""
    text: Unknown command...

  menu:
    title: Available Options
    checkButton:
      title: Check my subscribed topics âœ…
      value: check
    listButton:
      title: List every available topic ğŸ”˜
      value: list
    resetButton:
      title: Reset all my subscribed topics âŒ
      value: reset
