cards:
  welcomeCard:
    title: Private Notifications Center
    text: Lorem Ipsum

  unknownCard:
    title: ""
    text: Unknown command...

  menuCard:
    title: Available Options
    checkButton:
      title: CHECK my subscribed topics ğŸ§¾
      value: CHECK
    resetButton:
      title: RESET all my subscribed topics âŒ
      value: RESET
    subscriptionButtons:
      - title: Subscribe to LATAM notifications ğŸ‡¦ğŸ‡·
        value: LATAM
      - title: Subscribe to UK notifications ğŸ‡¬ğŸ‡§
        value: UK
      - title: Subscribe to SPAIN notifications ğŸ‡ªğŸ‡¸
        value: SPAIN
      - title: Subscribe to GERMANY notifications ğŸ‡©ğŸ‡ª
        value: GERMANY
